As an admin, I want to manage warehouse data
purwadhikafullstack/JCWDOL01101 pull request #11
Opened 2023-11-25 06:53 UTC by evelioexcellenta

2023-11-25 07:00 UTC, Beru088 approved these changes

2023-11-25 08:57 UTC, putuhema requested changes
ada banyak code yang di comment, mungki cek ulang atau dihapus

2023-11-26 13:01 UTC, Beru088 requested changes
ada // ketinggalan di ware house type, sama button nggak kepake masih di comment.

2023-11-26 13:09 UTC, Beru088 approved these changes

2023-11-26 14:34 UTC, putuhema approved these changes

2023-11-26 15:04 UTC, merged